"""The committed sample corpus must stay usable as the schema moves.

`examples/sample-corpus/` ships two episodes -- transcripts, summaries, mentions
and a SQLite index -- so a reader or an agent can query the tools without first
running a download-and-transcribe pipeline. It is generated by
`examples/generate_sample_corpus.py` calling the real core functions, which
keeps it schema-correct *at the moment it is generated* and not one commit
after.

Nothing re-runs that generator on its own, so until this file existed the
corpus could go stale silently: a schema change would leave the committed
artifacts describing a shape the code no longer reads, and the first person to
notice would be someone following the README. These tests read the committed
bytes through the same entry points a user reaches for, so the corpus fails
here instead.

They deliberately do not re-run the generator. Regenerating and diffing would
test that the generator is deterministic; what needs guarding is that the
*committed* files still parse, still index, and still answer a query.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SAMPLE_DATA = REPO_ROOT / "examples" / "sample-corpus" / "data"
SAMPLE_DB = SAMPLE_DATA / "cache" / "podcast_ingest.sqlite3"
PODCAST_ID = "sample"

EPISODES = {
    "SAMPLE-001": "Harbour Robotics and the GPU hour",
    "SAMPLE-002": "Northwind Logistics and the CPI print",
}

# Written by cache.rebuild_cache. transcript_segments_fts* are FTS5 shadow
# tables and are checked as a group rather than by name, since SQLite's set of
# shadow tables is an implementation detail of the FTS version.
REQUIRED_TABLES = {"episodes", "mentions", "mention_evidence", "transcript_segments"}


@pytest.fixture
def sample_storage(monkeypatch: pytest.MonkeyPatch):
    """Repoint the artifact roots at the committed corpus.

    Monkeypatching the ``storage`` constants is the sanctioned way to move the
    roots for a test -- see ``tests/conftest.py``. CORPUS_INGEST_DATA_DIR is
    read at import time, too late here, and conftest fails the whole run when
    it is set.
    """

    from corpus_ingest_core import storage

    monkeypatch.setattr(storage, "DATA_DIR", SAMPLE_DATA)
    for name, relative in (
        ("AUDIO_DIR", "audio"),
        ("TRANSCRIPTS_DIR", "transcripts"),
        ("SUMMARIES_DIR", "summaries"),
        ("MENTIONS_DIR", "mentions"),
        ("REPORTS_DIR", "reports"),
        ("CACHE_DIR", "cache"),
        ("CORPUS_DIR", "corpus"),
    ):
        if hasattr(storage, name):
            monkeypatch.setattr(storage, name, SAMPLE_DATA / relative)
    return storage


def test_sample_corpus_is_present_and_ships_no_audio():
    """The corpus starts at the transcript stage; audio is never committed."""

    assert SAMPLE_DATA.is_dir(), "the committed sample corpus is missing"

    media = sorted(
        path.name
        for path in SAMPLE_DATA.rglob("*")
        if path.suffix.lower() in {".mp3", ".m4a", ".wav", ".aac", ".flac"}
    )
    assert not media, f"audio must not be committed: {media}"


@pytest.mark.parametrize("episode_ref", sorted(EPISODES))
def test_committed_transcript_still_validates(episode_ref: str, sample_storage):
    """The real validator, against the committed bytes.

    This is the check that catches a schema move: validate_transcript resolves
    the canonical paths and reads the JSON the current code expects, so a
    renamed field or a changed slug rule fails here.
    """

    from corpus_ingest_core.validator import validate_transcript

    result = validate_transcript(PODCAST_ID, episode_ref)

    assert result.status == "valid", (
        f"{episode_ref} no longer validates ({result.status}): {result.problems}. "
        "Re-run examples/generate_sample_corpus.py and commit the result."
    )
    assert result.segment_count > 0
    assert not result.problems


@pytest.mark.parametrize("episode_ref,title", sorted(EPISODES.items()))
def test_committed_files_sit_where_storage_looks_for_them(
    episode_ref: str, title: str, sample_storage
):
    """A slug-rule change would orphan these files: present, but unreachable."""

    storage = sample_storage
    transcripts = storage.transcript_asset_paths(PODCAST_ID, episode_ref, title)

    for path in (transcripts.text_path, transcripts.srt_path, transcripts.json_path):
        assert path.is_file(), f"storage resolves {path.name}, which is not committed"

    summary = storage.summary_asset_path(PODCAST_ID, episode_ref, title)
    assert summary.is_file(), f"storage resolves {summary.name}, which is not committed"


def test_committed_index_answers_a_transcript_search():
    """The committed SQLite index must still return timestamped evidence."""

    from corpus_ingest_core.search import search_transcripts

    results = search_transcripts(
        "harbour", podcast_id=PODCAST_ID, limit=5, db_path=SAMPLE_DB
    )

    assert results, (
        "the committed index returned nothing for a term the sample transcripts "
        "contain -- it is stale. Re-run examples/generate_sample_corpus.py."
    )
    for hit in results:
        assert hit.episode_ref in EPISODES
        assert hit.timestamp, "every transcript hit must carry timestamp evidence"


def test_committed_index_answers_a_mention_search():
    from corpus_ingest_core.search import search_mentions

    results = search_mentions("GPU", podcast_id=PODCAST_ID, limit=5, db_path=SAMPLE_DB)

    assert results, "the committed index has no mention evidence for 'GPU'"
    for hit in results:
        assert hit.episode_ref in EPISODES
        assert hit.evidence_timestamp


def test_committed_index_carries_the_tables_the_readers_query():
    """Opened read-only. A migration leaves the committed file behind, and a
    search would then fail with a SQL error rather than an empty result.
    """

    assert SAMPLE_DB.is_file(), "the committed SQLite index is missing"

    connection = sqlite3.connect(f"file:{SAMPLE_DB}?mode=ro", uri=True)
    try:
        committed = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            )
        }
    finally:
        connection.close()

    missing = REQUIRED_TABLES - committed
    assert not missing, (
        f"the committed index is missing {sorted(missing)}. Re-run "
        "examples/generate_sample_corpus.py and commit the result."
    )
    assert any(name.startswith("transcript_segments_fts") for name in committed), (
        "the committed index has no FTS5 tables, so search falls back to LIKE"
    )


def test_transcripts_name_no_real_company_or_ticker():
    """The corpus is fictional on purpose, and must stay that way.

    Committing a real show's transcript would be republishing someone's
    copyrighted work, and putting a real listed company into invented
    commentary is its own problem. The extractor's own vocabulary is the
    oracle: whatever it recognises as a real company or ticker must not appear.
    """

    from corpus_ingest_core.entity_extractor import MENTION_RULES

    forbidden = {
        str(term).casefold()
        for rule_type in ("company", "stock_or_ticker")
        for term in MENTION_RULES.get(rule_type, {})
    }
    if not forbidden:
        pytest.skip("extractor vocabulary is empty; nothing to compare against")

    offenders: set[str] = set()
    for path in sorted((SAMPLE_DATA / "transcripts" / PODCAST_ID).glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        body = " ".join(segment["text"] for segment in payload["segments"]).casefold()
        offenders.update(term for term in forbidden if term in body)

    assert not offenders, (
        f"the sample transcripts name real entities: {sorted(offenders)}. "
        "Every company in this corpus must be invented."
    )
